Added missing dependencies as directory resources.
Error: Could not find dependency File[/opt] for Archive[roundcubemail-1.1.5-complete] at /etc/puppet/modules/roundcube/manifests/install.pp:52

Error: Cannot create /var/cache/puppet/archives; parent directory /var/cache/puppet does not exist
Error: /Stage[main]/Roundcube::Params/File[/var/cache/puppet/archives]/ensure: change from absent to directory failed: Cannot create /var/cache/puppet/archives; parent directory /var/cache/puppet does not exist